apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  RABBITMQ_HOST: "helm-rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_QUEUE: "user_queue"
  RABBITMQ_DEFAULT_USER: "apiuser"
  RABBITMQ_DEFAULT_PASS: "apipassword"
  RABBITMQ_DEFAULT_VHOST: "/"
  # Add additional permissions if needed
  RABBITMQ_DEFAULT_PERMISSIONS: ".* .* .*"
  # Management console user credentials
  RABBITMQ_MANAGEMENT_USER: "admin"
  RABBITMQ_MANAGEMENT_PASS: "your_updated_password"
