apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stat-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stat-api-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
